GET http://localhost:8080/school/cuestionarios
Accept: application/json

###

GET http://localhost:8080/school/cuestionarios/502
Accept: application/json

###

POST http://localhost:8080/school/cuestionarios
Accept: application/json
Content-Type: application/json

{
  "titulo": "Cuestionario 4",
  "notaMinima": 5
}

###

GET http://localhost:8080/school/cuestionarios/502/preguntas
Accept: application/json

###

PUT http://localhost:8080/school/cuestionarios/503/preguntas
Accept: application/json
Content-Type: application/json

{
  "preguntaId": 552,
  "orden": 10
}